### ISSUE TITLE
Prerelease Nice-To-Haves

### ISSUE THREAD

**Issue by ichristen** [QPG-MIT/slmsuite#2]
## Nice to haves:
 - [x] Test SLM blitting speed
   - [x] Add a function to write a video to the SLM, potentially triggered (moved to #12).
- [x] take wavefront_calibrate helpers outside of function, make them private static methods - @ichristen  thinks this is low priority, as these functions are never seen by the user. Maybe this can be done after release, if it's clean.
- [x] automatic black formatting (edit: future problem. not now)
- [x] make a config file for dll paths, possibly add an install script (will revisit based on user feedback).
 - [x] Make logo dark-theme compatible.
 - [x] Resolve verboseness: consider a flag in each class with default verboseness.
   - [x] Simplified this a bit. Removed saving entirely.
 - [x] Example or guide for aligning SLMs.
 - [x] Implement FILR cameras (moved to #20 ).
 - [x] Add `info()` functions to help identify cameras and displays (class methods).
   - [x] Done for SantecSLM, but not for others.
 - [x] Free running camera window, for alignment (need to think carefully about this). (Moved to #7 and `pygletcamera` branch 381af3ed4bf562bd1b6e7d249844ff88eebdda9f) 
 - [x] Add links (DOI) to literature references.
 - [x] `thresh` vs `threshold`?
 - [x] .rst uses ``test`` (two grave) for monospace instead of `test` (one grave). Convert docstrings to the former.
 - [x] `hone` option for Fourier calibration, to fit to FFT and convolution -produced guess.
 - [x] Fourier calibration should error more elegantly when over or under exposed.
 - [x] Method to measure SLM settle time.
   - [x] (partially implemented)
 - [x] Resolve nested loop tqdm in wavefront calibration.
 - [x] Rename `lcos_toolbox` to `toolbox` and `image_analysis` to `analysis`
 - [x] Make the Zoom axis in plot_farfield red to match the red box.
 - [x] Label the yellow camera box in plot_farfield. Probably with a legend.
 - [x] ~Consider removing cv2 dependencies in favor of numpy/scipy (esp. cupy-accelerated).~ Decided against.
 - [x] Should plots have white backgrounds instead of transparent? (edit: future problem. not now)
   - [x] Maybe the plot keyword can be passed a dict which is then passed to all figures/etc. (edit: future problem. not now)
 - [x] Look into allowing external people to test the package on a live SLM (e.g. basement setup). (decided against)
 - [x] Add SLM tips page (setup, alignment, screen timeout, mouseover errors, and other institutional knowledge)
 - [x] Add FAQ page (moved for later, Tips for now).
 - [x] Stats plotting colors
 - [x] Unified figure size / etc solution, esp. for outside of jupyter (moved to future work, once someone complains).
 - [x] Add option to `wavefront_calibration()` to only gather `measured_amplitude`.
